/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.035, 0.251]} scale={175.486}>
        <group scale={0.002}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-4.428, 5.164, -0.536]}>
              <mesh geometry={nodes['����������_����������_Material_#44_0'].geometry} material={materials.Material_44} />
              <mesh geometry={nodes['����������_����������_Material_#43_0'].geometry} material={materials.Material_43} />
              <mesh geometry={nodes['����������_����������_Material_#42_0'].geometry} material={materials.Material_42} />
              <mesh geometry={nodes['����������_����������_Material_#41_0'].geometry} material={materials.Material_41} />
              <mesh geometry={nodes['����������_����������_Material_#45_0'].geometry} material={materials.Material_45} />
            </group>
            <group position={[4.42, 5.176, -0.496]}>
              <mesh geometry={nodes['������������_����������_Material_#39_0'].geometry} material={materials.Material_39} />
              <mesh geometry={nodes['������������_����������_Material_#38_0'].geometry} material={materials.Material_38} />
              <mesh geometry={nodes['������������_����������_Material_#37_0'].geometry} material={materials.Material_37} />
              <mesh geometry={nodes['������������_����������_Material_#34_0'].geometry} material={materials.Material_34} />
              <mesh geometry={nodes['������������_����������_Material_#40_0'].geometry} material={materials.Material_40} />
            </group>
            <group position={[3.943, 7.414, -1.576]}>
              <mesh geometry={nodes['������������_Material_#46_0'].geometry} material={materials.Material_46} />
              <mesh geometry={nodes['������������_Material_#47_0'].geometry} material={materials.Material_47} />
              <mesh geometry={nodes['������������_Material_#48_0'].geometry} material={materials.Material_48} />
              <mesh geometry={nodes['������������_Material_#49_0'].geometry} material={materials.Material_49} />
              <mesh geometry={nodes['������������_Material_#50_0'].geometry} material={materials.Material_50} />
            </group>
            <group position={[-3.94, 7.414, -1.576]} scale={[-1, 1, 1]}>
              <mesh geometry={nodes['������������_Material_#46_0_1'].geometry} material={materials.Material_46} />
              <mesh geometry={nodes['������������_Material_#47_0_1'].geometry} material={materials.Material_47} />
              <mesh geometry={nodes['������������_Material_#48_0_1'].geometry} material={materials.Material_48} />
              <mesh geometry={nodes['������������_Material_#49_0_1'].geometry} material={materials.Material_49} />
              <mesh geometry={nodes['������������_Material_#50_0_1'].geometry} material={materials.Material_50} />
            </group>
            <group position={[3.943, -4.888, -1.576]}>
              <mesh geometry={nodes['������������_Material_#46_0_2'].geometry} material={materials.Material_46} />
              <mesh geometry={nodes['������������_Material_#47_0_2'].geometry} material={materials.Material_47} />
              <mesh geometry={nodes['������������_Material_#48_0_2'].geometry} material={materials.Material_48} />
              <mesh geometry={nodes['������������_Material_#49_0_2'].geometry} material={materials.Material_49} />
              <mesh geometry={nodes['������������_Material_#50_0_2'].geometry} material={materials.Material_50} />
            </group>
            <group position={[-3.94, -4.888, -1.576]} scale={[-1, 1, 1]}>
              <mesh geometry={nodes['������������_Material_#46_0_3'].geometry} material={materials.Material_46} />
              <mesh geometry={nodes['������������_Material_#47_0_3'].geometry} material={materials.Material_47} />
              <mesh geometry={nodes['������������_Material_#48_0_3'].geometry} material={materials.Material_48} />
              <mesh geometry={nodes['������������_Material_#49_0_3'].geometry} material={materials.Material_49} />
              <mesh geometry={nodes['������������_Material_#50_0_3'].geometry} material={materials.Material_50} />
            </group>
            <mesh geometry={nodes['����������_Material_#32_0'].geometry} material={materials.Material_32} />
            <mesh geometry={nodes['����������_Material_#29_0'].geometry} material={materials.Material_29} />
            <mesh geometry={nodes['����������_Material_#30_0'].geometry} material={materials.Material_30} />
            <mesh geometry={nodes['����������_Material_#33_0'].geometry} material={materials.Material_33} />
            <mesh geometry={nodes['����������_Material_#28_0'].geometry} material={materials.Material_28} />
            <mesh geometry={nodes['����������_Material_#31_0'].geometry} material={materials.Material_31} />
            <mesh geometry={nodes['����������_Material_#35_0'].geometry} material={materials.Material_35} />
            <mesh geometry={nodes['����������_Material_#36_0'].geometry} material={materials.Material_36} />
            <mesh geometry={nodes['��������_Material_#11_0'].geometry} material={materials.Material_11} scale={[-1, 1, 1]} />
            <mesh geometry={nodes['��������_Material_#10_0'].geometry} material={materials.Material_10} scale={[-1, 1, 1]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
